package timetable;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Add_Student extends javax.swing.JFrame {

    /**
     * Creates new form Add_Student
     */
    public Add_Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jtxtGID = new javax.swing.JTextField();
        jtxtSGID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Manage Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add Student");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Academic Year and Semester");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Programme");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Group Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sub Group Number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Group ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Sub Group ID");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1 Semester 1", "Year 1 Semester 2", "Year 2 Semester 1", "Year 2 Semester 2", "Year 3 Semester 1", "Year 3 Semester 2", "Year 4 Semester 1", "Year 4 Semester 2" }));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Information Technology", "Software Engineering", "Cyber Security", "Data Science", "Information System Engineering", "Computer System & Network Engineering" }));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        jtxtGID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtxtSGID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSGID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSGIDActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("Generate ID");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtxtGID, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtSGID, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(461, 461, 461))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtGID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSGID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
            String ys =jComboBox1.getSelectedItem().toString();
            String pro = jComboBox2.getSelectedItem().toString();
            String Gnum = jComboBox3.getSelectedItem().toString();
            String SGnum = jComboBox4.getSelectedItem().toString();
            String groupID = jtxtGID.getText();
            String subgroupID = jtxtSGID.getText();
            
            
             
          
            
                try{
                    
        if(ys.equals("")||pro.equals("") || Gnum.equals("") || SGnum.equals("") || groupID.equals("")||subgroupID.equals("")){  //Input field validation
        
        JOptionPane.showMessageDialog(this, "Input fields cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
        }else{
              
  
         
             MY_CONNECTION.setData("Insert into student values('0','"+jComboBox1.getSelectedItem().toString()+"','"+jComboBox2.getSelectedItem().toString()+"','"+jComboBox3.getSelectedItem().toString()+"','"+jComboBox4.getSelectedItem().toString()+"','"+jtxtGID.getText()+"','"+jtxtSGID.getText()+"')");
             //table_update();
             
             jComboBox1.setSelectedIndex(0);
             jComboBox2.setSelectedIndex(0);
             
             jComboBox3.setSelectedIndex(0);
             jComboBox4.setSelectedIndex(0);
             jtxtGID.setText("");
             jtxtSGID.setText("");
                
        //success msg
        JOptionPane.showMessageDialog(this, " added succesfully","Successful",JOptionPane.INFORMATION_MESSAGE);
       
        }
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(this, "Invalid Input.Re enter details.","Error",JOptionPane.ERROR_MESSAGE);
        System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //Manage_Student C = new Manage_Student();
        //this.hide();
        //C.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         Timetable C = new Timetable();
       this.hide();
       C.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try{
            String ys = (String) jComboBox1.getSelectedItem();
            String pro = (String) jComboBox2.getSelectedItem();
            String Gnum = (String) jComboBox3.getSelectedItem();
            String SGnum = (String) jComboBox4.getSelectedItem();
            
         if(pro == "Information Technology"){
            if (ys == "Year 1 Semester 1"){
             String dis1 = "Y1.S1."+"IT."+Gnum;
             jtxtGID.setText(dis1);
              
             String dis2 = "Y1.S1."+"IT."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 1 Semester 2"){
             String dis1 = "Y1.S2."+"IT."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y1.S2."+"IT."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 1"){
             String dis1 = "Y2.S1."+"IT."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S1."+"IT."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 2"){
             String dis1 = "Y2.S2."+"IT."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S2."+"IT."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 1"){
             String dis1 = "Y3.S1."+"IT."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S1."+"IT."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 2"){
             String dis1 = "Y3.S2."+"IT."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S2."+"IT."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 1"){
             String dis1 = "Y4.S1."+"IT."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S1."+"IT."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 2"){
             String dis1 = "Y4.S2."+"IT."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S2."+"IT."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
         }
         else if(pro == "Cyber Security"){
            if (ys == "Year 1 Semester 1"){
             String dis1 = "Y1.S1."+"CS."+Gnum;
             jtxtGID.setText(dis1);
              
             String dis2 = "Y1.S1."+"CS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 1 Semester 2"){
             String dis1 = "Y1.S2."+"CS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y1.S2."+"CS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 1"){
             String dis1 = "Y2.S1."+"CS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S1."+"CS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 2"){
             String dis1 = "Y2.S2."+"CS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S2."+"CS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 1"){
             String dis1 = "Y3.S1."+"CS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S1."+"CS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 2"){
             String dis1 = "Y3.S2."+"CS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S2."+"CS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 1"){
             String dis1 = "Y4.S1."+"CS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S1."+"CS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 2"){
             String dis1 = "Y4.S2."+"CS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S2."+"CS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
         }
         else if(pro == "Data Science"){
            if (ys == "Year 1 Semester 1"){
             String dis1 = "Y1.S1."+"DS."+Gnum;
             jtxtGID.setText(dis1);
              
             String dis2 = "Y1.S1."+"DS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 1 Semester 2"){
             String dis1 = "Y1.S2."+"DS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y1.S2."+"DS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 1"){
             String dis1 = "Y2.S1."+"DS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S1."+"DS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 2"){
             String dis1 = "Y2.S2."+"DS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S2."+"DS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 1"){
             String dis1 = "Y3.S1."+"DS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S1."+"DS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 2"){
             String dis1 = "Y3.S2."+"DS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S2."+"DS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 1"){
             String dis1 = "Y4.S1."+"DS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S1."+"DS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 2"){
             String dis1 = "Y4.S2."+"DS."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S2."+"DS."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
         }
         else if(pro == "Information System Engineering"){
            if (ys == "Year 1 Semester 1"){
             String dis1 = "Y1.S1."+"ISE."+Gnum;
             jtxtGID.setText(dis1);
              
             String dis2 = "Y1.S1."+"ISE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 1 Semester 2"){
             String dis1 = "Y1.S2."+"ISE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y1.S2."+"ISE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 1"){
             String dis1 = "Y2.S1."+"ISE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S1."+"ISE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 2"){
             String dis1 = "Y2.S2."+"ISE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S2."+"ISE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 1"){
             String dis1 = "Y3.S1."+"ISE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S1."+"ISE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 2"){
             String dis1 = "Y3.S2."+"ISE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S2."+"ISE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 1"){
             String dis1 = "Y4.S1."+"ISE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S1."+"ISE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 2"){
             String dis1 = "Y4.S2."+"ISE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S2."+"ISE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
         }
         else if(pro == "Computer System & Network Engineering"){
            if (ys == "Year 1 Semester 1"){
             String dis1 = "Y1.S1."+"CSNE."+Gnum;
             jtxtGID.setText(dis1);
              
             String dis2 = "Y1.S1."+"CSNE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 1 Semester 2"){
             String dis1 = "Y1.S2."+"CSNE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y1.S2."+"CSNE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 1"){
             String dis1 = "Y2.S1."+"CSNE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S1."+"CSNE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 2 Semester 2"){
             String dis1 = "Y2.S2."+"CSNE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y2.S2."+"CSNE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 1"){
             String dis1 = "Y3.S1."+"CSNE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S1."+"CSNE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 3 Semester 2"){
             String dis1 = "Y3.S2."+"CSNE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y3.S2."+"CSNE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 1"){
             String dis1 = "Y4.S1."+"CSNE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S1."+"CSNE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
            else if (ys == "Year 4 Semester 2"){
             String dis1 = "Y4.S2."+"CSNE."+Gnum;
             jtxtGID.setText(dis1);
             
             String dis2 = "Y4.S2."+"CSNE."+Gnum+"."+SGnum;
             jtxtSGID.setText(dis2);
            }
         }
        }catch(Exception e){
            System.out.println("inside");
            JOptionPane.showMessageDialog(null, "Incorrect Inputs");
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jtxtSGIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSGIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSGIDActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        jComboBox1.setSelectedIndex(0);
             jComboBox2.setSelectedIndex(0);
             
             jComboBox3.setSelectedIndex(0);
             jComboBox4.setSelectedIndex(0);
             jtxtGID.setText("");
             jtxtSGID.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtxtGID;
    private javax.swing.JTextField jtxtSGID;
    // End of variables declaration//GEN-END:variables
}
