package timetable;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ManageLecturer extends javax.swing.JFrame {

    /**
     * Creates new form ManageLecturer
     */
    public ManageLecturer() {
        initComponents();
        
        
        table_update();
        
        
        
    }
    
    
    Connection conl;
PreparedStatement pst;
    
    
    
    
    
    private void table_update(){
try{

ResultSet rs= MY_CONNECTION.getData("Select * from add_lecturer");
DefaultTableModel tm = (DefaultTableModel)jTableManageLecturer.getModel();
tm.setRowCount(0);


Object[] column = new Object[9];
while(rs.next()){


column[0] = rs.getString("lname");
column[1] = rs.getInt("eID");
column[2] = rs.getString("Department");
column[3] = rs.getString("activeHours");
column[4] = rs.getString("faculty");
column[5] = rs.getString("center");
column[6] = rs.getString("building");
column[7] = rs.getString("level");
column[8] = rs.getString("rank");

tm.addRow(column);
}

}catch(Exception e){
JOptionPane.showMessageDialog(this,e);
System.out.println(e);
}

}

private void table_update(int x) {
throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
}



//Search



private void table_search(){
try{

    String lecName = jTextFieldLecturerName.getText();
    
ResultSet rs= MY_CONNECTION.getData("Select * from add_lecturer WHERE lname like '%"+lecName+"%'");
DefaultTableModel tm = (DefaultTableModel)jTableManageLecturer.getModel();
tm.setRowCount(0);


Object[] column = new Object[9];
while(rs.next()){


column[0] = rs.getString("lname");
column[1] = rs.getInt("eID");
column[2] = rs.getString("Department");
column[3] = rs.getString("activeHours");
column[4] = rs.getString("faculty");
column[5] = rs.getString("center");
column[6] = rs.getString("building");
column[7] = rs.getString("level");
column[8] = rs.getString("rank");

tm.addRow(column);
}

}catch(Exception e){
JOptionPane.showMessageDialog(this,e);
System.out.println(e);
}

}




    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnHomeAL = new javax.swing.JButton();
        btnAddLecturer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManageLecturer = new javax.swing.JTable();
        lbManageLecturer = new javax.swing.JLabel();
        lLecturerName = new javax.swing.JLabel();
        txtLecturerNameML = new javax.swing.JTextField();
        lCenter = new javax.swing.JLabel();
        cbCenterML = new javax.swing.JComboBox<>();
        cbBuildingML = new javax.swing.JComboBox<>();
        lBuilding = new javax.swing.JLabel();
        txtEmployeeIDML = new javax.swing.JTextField();
        lEmployeeID = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lDepartment = new javax.swing.JLabel();
        cbDepartmentML = new javax.swing.JComboBox<>();
        lActiveHours = new javax.swing.JLabel();
        cbActiveHoursML = new javax.swing.JComboBox<>();
        lFaculty = new javax.swing.JLabel();
        cbFacultyML = new javax.swing.JComboBox<>();
        lLevel = new javax.swing.JLabel();
        txtLevelML = new javax.swing.JTextField();
        lRank = new javax.swing.JLabel();
        txtRankML = new javax.swing.JTextField();
        lbLecturerNameML = new javax.swing.JLabel();
        jTextFieldLecturerName = new javax.swing.JTextField();
        btnClearAL = new javax.swing.JButton();
        lHoursML = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnHomeAL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHomeAL.setText("Home");
        btnHomeAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeALActionPerformed(evt);
            }
        });

        btnAddLecturer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddLecturer.setText("Add Lecturer");
        btnAddLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLecturerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                .addComponent(btnHomeAL, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnAddLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomeAL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTableManageLecturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Lecturer Name", "Employee ID", "Department", "Active Hours", "Faculty", "Center", "Building", "Level", "Rank"
            }
        ));
        jTableManageLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableManageLecturerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableManageLecturer);

        lbManageLecturer.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbManageLecturer.setText("Manage Lecturer");

        lLecturerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lLecturerName.setText("Lecturer Name");

        txtLecturerNameML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLecturerNameMLActionPerformed(evt);
            }
        });

        lCenter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lCenter.setText("Center");

        cbCenterML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Center", "Malabe", "Matara", "Jaffna", "Metro", "Kurunagala", "Kandy" }));

        cbBuildingML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Building", "Block A", "Block B", "Block E", "Block F" }));
        cbBuildingML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuildingMLActionPerformed(evt);
            }
        });

        lBuilding.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lBuilding.setText("Building");

        txtEmployeeIDML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDMLActionPerformed(evt);
            }
        });

        lEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lEmployeeID.setText("Employee ID");

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lDepartment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lDepartment.setText("Department");

        cbDepartmentML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Department", "IT", "SE", "ISE", "IM", "DS", "CS", "CSNE", "QS" }));
        cbDepartmentML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartmentMLActionPerformed(evt);
            }
        });

        lActiveHours.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lActiveHours.setText("Active hours");

        cbActiveHoursML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active Hours", "1", "2", "3", " " }));
        cbActiveHoursML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActiveHoursMLActionPerformed(evt);
            }
        });

        lFaculty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lFaculty.setText("Faculty");

        cbFacultyML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty", "Computing", "Business", "Engineering", "Architechture", "Humanities and Science" }));
        cbFacultyML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFacultyMLActionPerformed(evt);
            }
        });

        lLevel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lLevel.setText("Level");

        lRank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lRank.setText("Rank");

        lbLecturerNameML.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLecturerNameML.setText("Lecturer Name");

        jTextFieldLecturerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLecturerNameKeyPressed(evt);
            }
        });

        btnClearAL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnClearAL.setText("Clear");
        btnClearAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearALActionPerformed(evt);
            }
        });

        lHoursML.setText("Hours");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lLecturerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lEmployeeID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lActiveHours, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbDepartmentML, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbFacultyML, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbActiveHoursML, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lHoursML, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lRank, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLecturerNameML)
                                    .addComponent(txtEmployeeIDML, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lBuilding, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbCenterML, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbBuildingML, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLevelML)
                                .addComponent(txtRankML, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(btnClearAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(lbLecturerNameML, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jTextFieldLecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbManageLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbManageLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLecturerNameML, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(lCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(lLecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtLecturerNameML, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmployeeIDML, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbDepartmentML, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lActiveHours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbActiveHoursML, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lHoursML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbFacultyML, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lLevel)
                                            .addComponent(txtLevelML, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lRank, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRankML, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbCenterML, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbBuildingML, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnClearAL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableManageLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableManageLecturerMouseClicked
        // TODO add your handling code here:
        
        
        DefaultTableModel d1 =(DefaultTableModel)jTableManageLecturer.getModel();
int selectIndex =jTableManageLecturer.getSelectedRow();

txtLecturerNameML.setText(d1.getValueAt(selectIndex, 0).toString());
txtEmployeeIDML.setText(d1.getValueAt(selectIndex, 1).toString());
cbDepartmentML.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
cbActiveHoursML.setSelectedItem(d1.getValueAt(selectIndex, 3).toString());
cbFacultyML.setSelectedItem(d1.getValueAt(selectIndex, 4).toString());
cbCenterML.setSelectedItem(d1.getValueAt(selectIndex, 5).toString());
cbBuildingML.setSelectedItem(d1.getValueAt(selectIndex, 6).toString());
txtLevelML.setText(d1.getValueAt(selectIndex, 7).toString());
txtRankML.setText(d1.getValueAt(selectIndex, 8).toString());

/*Faculty1.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
Department1.setSelectedItem(d1.getValueAt(selectIndex, 3).toString());
center1.setSelectedItem(d1.getValueAt(selectIndex, 4).toString());
level1.setSelectedItem(d1.getValueAt(selectIndex, 5).toString());
Bulding1.setSelectedItem(d1.getValueAt(selectIndex, 6).toString());
Rank1.setText(d1.getValueAt(selectIndex, 7).toString());*/
        
        
        
        
        
        
    }//GEN-LAST:event_jTableManageLecturerMouseClicked

    private void txtLecturerNameMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLecturerNameMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLecturerNameMLActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel d1 =(DefaultTableModel)jTableManageLecturer.getModel();
int selectIndex =jTableManageLecturer.getSelectedRow();
int eID = Integer.parseInt(d1.getValueAt(selectIndex, 1).toString());

int dialogResult = JOptionPane.showConfirmDialog(null,"Do you need the delete","warning",JOptionPane.YES_NO_OPTION);

if(dialogResult == JOptionPane.YES_OPTION)
{
try {
    
    conl = MY_CONNECTION.getConnection();

pst = conl.prepareStatement("delete from add_lecturer where eID =?");
pst.setInt(1,eID);
pst.executeUpdate();
table_update();
txtLecturerNameML.setText("");
txtEmployeeIDML.setText("");
cbDepartmentML.setSelectedIndex(0);
cbActiveHoursML.setSelectedIndex(0);
cbFacultyML.setSelectedIndex(0);
cbCenterML.setSelectedIndex(0);
cbBuildingML.setSelectedIndex(0);
txtLevelML.setText("");
txtRankML.setText("");
//Bulding1.setSelectedIndex(0);

txtLecturerNameML.requestFocus();
}           catch (SQLException ex) {
                Logger.getLogger(ManageLecturer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ManageLecturer.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
}      
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        
        
        DefaultTableModel d1 =(DefaultTableModel)jTableManageLecturer.getModel();
int selectIndex =jTableManageLecturer.getSelectedRow();
int eID = Integer.parseInt(d1.getValueAt(selectIndex, 1).toString());
String name1 = txtLecturerNameML.getText();
String department1 = cbDepartmentML.getSelectedItem().toString();
String activeH = cbActiveHoursML.getSelectedItem().toString();
String faculty1 = cbFacultyML.getSelectedItem().toString();
String cnter1=cbCenterML.getSelectedItem().toString();
String bulding1 =cbBuildingML.getSelectedItem().toString();
String Level1 =txtLevelML.getText();


try{
if(name1.equals("")){
JOptionPane.showMessageDialog(null,"name is mondotory");
} else if(faculty1.equals("select")){
JOptionPane.showMessageDialog(null,"faculty is mondotory");
}else if(department1.equals("select")){
JOptionPane.showMessageDialog(null,"department is mondotory");
}else if(cnter1.endsWith("select")){
JOptionPane.showMessageDialog(null,"center is mondotory");

}else if(Level1.endsWith("select")){
JOptionPane.showMessageDialog(null,"Level is mondotory");

}else if(bulding1.endsWith("select")){
JOptionPane.showMessageDialog(null,"bulding is mondotory");
}else{ 
        Connection conl =MY_CONNECTION.getConnection();
        
pst = conl.prepareStatement("update add_lecturer set lname = ?,department=?,activeHours=? ,faculty=? ,center=?,building=?,level=? where eID= ?");
pst.setString(1,name1);
pst.setInt(8,eID);
pst.setString(2,department1);
pst.setString(3,activeH);
pst.setString(4,faculty1);

pst.setString(5,cnter1);
pst.setString(6,bulding1);
pst.setString(7,Level1);
//pst.setInt(7,eID);
pst.executeUpdate();
JOptionPane.showMessageDialog(null," Updatedd");
table_update();

//txtEmployeeIDML.setText("");
txtLecturerNameML.setText("");
txtEmployeeIDML.setText("");
//cbFacultyML.setSelectedIndex(0);
cbDepartmentML.setSelectedIndex(0);
cbFacultyML.setSelectedIndex(0);
cbActiveHoursML.setSelectedIndex(0);
cbCenterML.setSelectedIndex(0);
cbBuildingML.setSelectedIndex(0);
txtLevelML.setText("");

txtRankML.setText("");
txtLecturerNameML.requestFocus();
}
} 



       catch (Exception ex) {
            Logger.getLogger(ManageLecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
  
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtEmployeeIDMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDMLActionPerformed

    private void cbBuildingMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuildingMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBuildingMLActionPerformed

    private void cbDepartmentMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartmentMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepartmentMLActionPerformed

    private void cbActiveHoursMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActiveHoursMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActiveHoursMLActionPerformed

    private void jTextFieldLecturerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLecturerNameKeyPressed
        // TODO add your handling code here:
        
        table_search();
        
    }//GEN-LAST:event_jTextFieldLecturerNameKeyPressed

    private void btnAddLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLecturerActionPerformed
        // TODO add your handling code here:
        
        AddLecturer C = new AddLecturer();
        this.hide();
        C.setVisible(true);
        
    }//GEN-LAST:event_btnAddLecturerActionPerformed

    private void btnHomeALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeALActionPerformed
        // TODO add your handling code here:
        
        Timetable C = new Timetable();
       this.hide();
       C.setVisible(true);
        
    }//GEN-LAST:event_btnHomeALActionPerformed

    private void cbFacultyMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFacultyMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFacultyMLActionPerformed

    private void btnClearALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearALActionPerformed
        // TODO add your handling code here:
        
        txtEmployeeIDML.setText("");
txtLecturerNameML.setText("");
cbFacultyML.setSelectedIndex(-1);
cbDepartmentML.setSelectedIndex(-1);
cbCenterML.setSelectedIndex(-1);
txtLevelML.setText("");
cbBuildingML.setSelectedIndex(-1);
txtRankML.setText("");
cbActiveHoursML.setSelectedIndex(-1);
        
    }//GEN-LAST:event_btnClearALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageLecturer().setVisible(true);
            }
        });
    }
    
    
    
    



    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLecturer;
    private javax.swing.JButton btnClearAL;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHomeAL;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbActiveHoursML;
    private javax.swing.JComboBox<String> cbBuildingML;
    private javax.swing.JComboBox<String> cbCenterML;
    private javax.swing.JComboBox<String> cbDepartmentML;
    private javax.swing.JComboBox<String> cbFacultyML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableManageLecturer;
    private javax.swing.JTextField jTextFieldLecturerName;
    private javax.swing.JLabel lActiveHours;
    private javax.swing.JLabel lBuilding;
    private javax.swing.JLabel lCenter;
    private javax.swing.JLabel lDepartment;
    private javax.swing.JLabel lEmployeeID;
    private javax.swing.JLabel lFaculty;
    private javax.swing.JLabel lHoursML;
    private javax.swing.JLabel lLecturerName;
    private javax.swing.JLabel lLevel;
    private javax.swing.JLabel lRank;
    private javax.swing.JLabel lbLecturerNameML;
    private javax.swing.JLabel lbManageLecturer;
    private javax.swing.JTextField txtEmployeeIDML;
    private javax.swing.JTextField txtLecturerNameML;
    private javax.swing.JTextField txtLevelML;
    private javax.swing.JTextField txtRankML;
    // End of variables declaration//GEN-END:variables
}
