package timetable;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.runtime.Debug.id;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ManageSubjects extends javax.swing.JFrame {

    /**
     * Creates new form ManageSubjects
     */
    public ManageSubjects() {
        initComponents();
        
        table_update();
        
    }
    
    
    Connection conl;
PreparedStatement pst;


private void table_update(){
try{

ResultSet rs= MY_CONNECTION.getData("Select * from subjects");
DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
tm.setRowCount(0);


Object[] column = new Object[9];
while(rs.next()){

column[0] = rs.getInt("id");
column[1] = rs.getString("subject_name");
column[2] = rs.getString("subject_code");
column[3] = rs.getString("offered_year");
column[4] = rs.getString("offered_semester");
column[5] = rs.getString("lecture_hours");
column[6] = rs.getString("tutorial_hours");
column[7] = rs.getString("lab_hours");
column[8] = rs.getString("evaluation_hours");



tm.addRow(column);
}

}catch(Exception e){
JOptionPane.showMessageDialog(this,e);
System.out.println(e);
}

}

private void table_update(int x) {
throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
}


//Search



private void table_search(){
try{

    String subCode = txtSubjectCodeSearch.getText();
    
ResultSet rs= MY_CONNECTION.getData("Select * from subjects WHERE subject_code like '%"+subCode+"%'");
DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
tm.setRowCount(0);


Object[] column = new Object[9];
while(rs.next()){


column[0] = rs.getInt("id");
column[1] = rs.getString("subject_name");
column[2] = rs.getString("subject_code");
column[3] = rs.getString("offered_year");
column[4] = rs.getString("offered_semester");
column[5] = rs.getString("lecture_hours");
column[6] = rs.getString("tutorial_hours");
column[7] = rs.getString("lab_hours");
column[8] = rs.getString("evaluation_hours");

tm.addRow(column);
}

}catch(Exception e){
JOptionPane.showMessageDialog(this,e);
System.out.println(e);
}

}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1MS = new javax.swing.JLabel();
        lOfferedSemesterMS = new javax.swing.JLabel();
        lSubjectNameMS = new javax.swing.JLabel();
        lSubjectCodeMS = new javax.swing.JLabel();
        txtSubjectCodeMS = new javax.swing.JTextField();
        txtSubjectNameMS = new javax.swing.JTextField();
        cbOfferedSemesterMS = new javax.swing.JComboBox<>();
        cbOfferedYearMS = new javax.swing.JComboBox<>();
        lLHoursMS = new javax.swing.JLabel();
        lThoursMS = new javax.swing.JLabel();
        lLabHoursMS = new javax.swing.JLabel();
        lEHoursMS = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lManageSubjectsMS = new javax.swing.JLabel();
        btnDeleteMS = new javax.swing.JButton();
        btnUpdateMS = new javax.swing.JButton();
        cbNumLecHMS = new javax.swing.JComboBox<>();
        cbNumTuteHMS = new javax.swing.JComboBox<>();
        cbNumLabHMS = new javax.swing.JComboBox<>();
        cbNumEvalHMS = new javax.swing.JComboBox<>();
        lSubjectCodeSearch = new javax.swing.JLabel();
        txtSubjectCodeSearch = new javax.swing.JTextField();
        btnClearMS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Add Subjects");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1MS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1MS.setText("Offered Year");

        lOfferedSemesterMS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lOfferedSemesterMS.setText("Offered Semester");

        lSubjectNameMS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lSubjectNameMS.setText("Subject Name");

        lSubjectCodeMS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lSubjectCodeMS.setText("Subject Code");

        txtSubjectCodeMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectCodeMSActionPerformed(evt);
            }
        });

        cbOfferedSemesterMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Offered Semester", "1", "2" }));

        cbOfferedYearMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Offered Year", "1", "2", "3", "4" }));

        lLHoursMS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lLHoursMS.setText("Number of Lecturer Hours");

        lThoursMS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lThoursMS.setText("Number of Tutorial Hours");

        lLabHoursMS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lLabHoursMS.setText("Number of Lab Hours");

        lEHoursMS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lEHoursMS.setText("Number of Evaluation Hours");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Subject Name", "Subject Code", "Offered Year", "Offered Semester", "Number of Lecture Hours", "Number of Tutorial Hours", "Number of Lab Hours", "Number of Evaluation Hours"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lManageSubjectsMS.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lManageSubjectsMS.setText("Manage Subjects");

        btnDeleteMS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDeleteMS.setText("Delete");
        btnDeleteMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMSActionPerformed(evt);
            }
        });

        btnUpdateMS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnUpdateMS.setText("Update");
        btnUpdateMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMSActionPerformed(evt);
            }
        });

        cbNumLecHMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Number of Lecture Hours", "0", "1", "2", "3" }));

        cbNumTuteHMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Number of Tutorial Hours", "0", "1", " " }));

        cbNumLabHMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Number of Lab Hours", "0", "1", "2", " " }));

        cbNumEvalHMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Number of Evaluation Hours", "0", "1", "2" }));

        lSubjectCodeSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lSubjectCodeSearch.setText("Subject Code");

        txtSubjectCodeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectCodeSearchActionPerformed(evt);
            }
        });
        txtSubjectCodeSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSubjectCodeSearchKeyPressed(evt);
            }
        });

        btnClearMS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnClearMS.setText("Clear");
        btnClearMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearMSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(lSubjectCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(txtSubjectCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lManageSubjectsMS, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1MS, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lOfferedSemesterMS, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lSubjectNameMS, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lSubjectCodeMS, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbOfferedYearMS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbOfferedSemesterMS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSubjectNameMS)
                            .addComponent(txtSubjectCodeMS, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lThoursMS, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lLHoursMS)
                            .addComponent(lLabHoursMS, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEHoursMS, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbNumLecHMS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNumTuteHMS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNumLabHMS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNumEvalHMS, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnUpdateMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lManageSubjectsMS, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSubjectCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubjectCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lLHoursMS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(lThoursMS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(lLabHoursMS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lEHoursMS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbNumEvalHMS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbNumLecHMS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80))
                                    .addComponent(cbNumTuteHMS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(cbNumLabHMS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1MS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbOfferedYearMS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lOfferedSemesterMS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbOfferedSemesterMS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lSubjectNameMS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubjectNameMS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSubjectCodeMS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lSubjectCodeMS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateMS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnDeleteMS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnClearMS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubjectCodeMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectCodeMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectCodeMSActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        
        
        DefaultTableModel d1 =(DefaultTableModel)jTable1.getModel();
int selectIndex =jTable1.getSelectedRow();

cbOfferedYearMS.setSelectedItem(d1.getValueAt(selectIndex, 3).toString());
cbOfferedSemesterMS.setSelectedItem(d1.getValueAt(selectIndex, 4).toString());
txtSubjectNameMS.setText(d1.getValueAt(selectIndex, 1).toString());
txtSubjectCodeMS.setText(d1.getValueAt(selectIndex, 2).toString());

cbNumLecHMS.setSelectedItem(d1.getValueAt(selectIndex, 5).toString());
cbNumTuteHMS.setSelectedItem(d1.getValueAt(selectIndex, 6).toString());
cbNumLabHMS.setSelectedItem(d1.getValueAt(selectIndex, 7).toString());
cbNumEvalHMS.setSelectedItem(d1.getValueAt(selectIndex, 8).toString());


       
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDeleteMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMSActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel d1 =(DefaultTableModel)jTable1.getModel();
int selectIndex =jTable1.getSelectedRow();
int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

int dialogResult = JOptionPane.showConfirmDialog(null,"Do you need the delete","warning",JOptionPane.YES_NO_OPTION);

if(dialogResult == JOptionPane.YES_OPTION)
{
try {
    
    conl = MY_CONNECTION.getConnection();

pst = conl.prepareStatement("delete from subjects where id =?");
pst.setInt(1,id);
pst.executeUpdate();
table_update();

cbOfferedYearMS.setSelectedIndex(0);
cbOfferedSemesterMS.setSelectedIndex(0);

txtSubjectNameMS.setText("");
txtSubjectCodeMS.setText("");

cbNumLecHMS.setSelectedIndex(0);
cbNumTuteHMS.setSelectedIndex(0);
cbNumLabHMS.setSelectedIndex(0);
cbNumEvalHMS.setSelectedIndex(0);

txtSubjectCodeMS.requestFocus();
}           catch (SQLException ex) {
                Logger.getLogger(ManageSubjects.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ManageSubjects.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
} 
        
        
    }//GEN-LAST:event_btnDeleteMSActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void btnUpdateMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMSActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel d1 =(DefaultTableModel)jTable1.getModel();
int selectIndex =jTable1.getSelectedRow();
int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

String offeredYear1 = cbOfferedYearMS.getSelectedItem().toString();
String offeredSemester1 = cbOfferedSemesterMS.getSelectedItem().toString();
String subjectname1 = txtSubjectNameMS.getText();
String subjectCode1 = txtSubjectCodeMS.getText();

String lecHours1 = cbNumLecHMS.getSelectedItem().toString();
String tutorialHours1 = cbNumTuteHMS.getSelectedItem().toString();
String labHours = cbNumLabHMS.getSelectedItem().toString();
String evaluationHours = cbNumEvalHMS.getSelectedItem().toString();




try{
if(offeredYear1.equals("")){
JOptionPane.showMessageDialog(null,"offered year is mondotory");
} else if(offeredSemester1.equals("select")){
JOptionPane.showMessageDialog(null,"offered semester is mondotory");
}else if(subjectname1.equals("select")){
JOptionPane.showMessageDialog(null,"subject name is mondotory");
}else if(subjectCode1.endsWith("select")){
JOptionPane.showMessageDialog(null,"subject code is mondotory");

}

else if(lecHours1.endsWith("select")){
JOptionPane.showMessageDialog(null,"lecture hours is mondotory");

}else if(tutorialHours1.endsWith("select")){
JOptionPane.showMessageDialog(null,"tutorial hours is mondotory");
}else if(labHours.endsWith("select")){
JOptionPane.showMessageDialog(null,"lab hours is mondotory");
}else if(evaluationHours.endsWith("select")){
JOptionPane.showMessageDialog(null,"evaluation hours is mondotory");
}

else{ 
        Connection conl =MY_CONNECTION.getConnection();
        
pst = conl.prepareStatement("update subjects set offered_year = ?,offered_semester=?, subject_name=? ,subject_code=? , lecture_hours = ?,tutorial_hours=?, lab_hours=? ,evaluation_hours=? where id= ?");
pst.setString(1,offeredYear1);
pst.setString(2,offeredSemester1);
pst.setString(3,subjectname1);
pst.setString(4,subjectCode1);

pst.setString(5,lecHours1);
pst.setString(6,tutorialHours1);
pst.setString(7,labHours);
pst.setString(8,evaluationHours);

pst.setInt(9,id);
pst.executeUpdate();
JOptionPane.showMessageDialog(null," Updated");
table_update();


cbOfferedYearMS.setSelectedIndex(0);
cbOfferedSemesterMS.setSelectedIndex(0);
txtSubjectNameMS.setText("");
txtSubjectCodeMS.setText("");
/*
sLHoursMS.setValue(0);
sTHoursMS.setValue(0);
SLabHoursMS.setValue(0);
sEHoursMS.setValue(0);
*/
}
} 



       catch (Exception ex) {
            Logger.getLogger(ManageLecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnUpdateMSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Timetable C = new Timetable();
       this.hide();
       C.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        AddSubjects C = new AddSubjects();
        this.hide();
        C.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void txtSubjectCodeSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubjectCodeSearchKeyPressed
        // TODO add your handling code here:
        
        table_search();
        
    }//GEN-LAST:event_txtSubjectCodeSearchKeyPressed

    private void btnClearMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearMSActionPerformed

    private void txtSubjectCodeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectCodeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectCodeSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSubjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearMS;
    private javax.swing.JButton btnDeleteMS;
    private javax.swing.JButton btnUpdateMS;
    private javax.swing.JComboBox<String> cbNumEvalHMS;
    private javax.swing.JComboBox<String> cbNumLabHMS;
    private javax.swing.JComboBox<String> cbNumLecHMS;
    private javax.swing.JComboBox<String> cbNumTuteHMS;
    private javax.swing.JComboBox<String> cbOfferedSemesterMS;
    private javax.swing.JComboBox<String> cbOfferedYearMS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1MS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lEHoursMS;
    private javax.swing.JLabel lLHoursMS;
    private javax.swing.JLabel lLabHoursMS;
    private javax.swing.JLabel lManageSubjectsMS;
    private javax.swing.JLabel lOfferedSemesterMS;
    private javax.swing.JLabel lSubjectCodeMS;
    private javax.swing.JLabel lSubjectCodeSearch;
    private javax.swing.JLabel lSubjectNameMS;
    private javax.swing.JLabel lThoursMS;
    private javax.swing.JTextField txtSubjectCodeMS;
    private javax.swing.JTextField txtSubjectCodeSearch;
    private javax.swing.JTextField txtSubjectNameMS;
    // End of variables declaration//GEN-END:variables
}
