package timetable;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Second_Window2 extends javax.swing.JFrame {

    /**
     * Creates new form Second_Window2
     */
    public Second_Window2() {
        initComponents();
        
         table_update();
         
         
    }
    
    Connection con1;
    PreparedStatement pst;
    
    private void table_update(){
try{

ResultSet rs= MY_CONNECTION.getData("Select * from addworkingdays_info");
DefaultTableModel tm = (DefaultTableModel)jTableManagmentWorkingdays.getModel();
tm.setRowCount(0);


Object[] column = new Object[11];
while(rs.next()){


column[1] = rs.getString("workingdays");
column[0] = rs.getInt("ID");
column[2] = rs.getString("hours");
column[3] = rs.getString("miniutes");
column[4] = rs.getInt("monday");
column[5] = rs.getInt("tuesday");
column[6] = rs.getInt("wednesday");
column[7] = rs.getInt("thursday");
column[8] = rs.getInt("friday");
column[9] = rs.getInt("saturday");
column[10] = rs.getInt("sunday");



tm.addRow(column);
}

}catch(Exception e){
JOptionPane.showMessageDialog(this,e);
System.out.println(e);
}

}

private void table_update(int x) {
throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
  //  private void jTableManagmentWorkingdaysMouseClicked(java.awt.event.MouseEvent evt){
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        workingdaysM1 = new javax.swing.JComboBox<>();
        mondayM = new javax.swing.JCheckBox();
        wednesdayM = new javax.swing.JCheckBox();
        tuesdayM = new javax.swing.JCheckBox();
        thursdayM = new javax.swing.JCheckBox();
        fridayM = new javax.swing.JCheckBox();
        saturdayM = new javax.swing.JCheckBox();
        sundayM = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        hoursM = new javax.swing.JTextField();
        miniutesM = new javax.swing.JTextField();
        jComboBoxM = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManagmentWorkingdays = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("ADD WORKING DAYS & HOURS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton4)
                .addGap(122, 122, 122))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setText("No of working days");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setText("weekdays");

        workingdaysM1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "22", "24", "26", "28", "30", "32", "34", "36", "38", "40" }));

        mondayM.setText("monday");

        wednesdayM.setText("wednesday");
        wednesdayM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayMActionPerformed(evt);
            }
        });

        tuesdayM.setText("tuesday");
        tuesdayM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayMActionPerformed(evt);
            }
        });

        thursdayM.setText("thursday");
        thursdayM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayMActionPerformed(evt);
            }
        });

        fridayM.setText("friday");
        fridayM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayMActionPerformed(evt);
            }
        });

        saturdayM.setText("saturday");
        saturdayM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayMActionPerformed(evt);
            }
        });

        sundayM.setText("sunday");
        sundayM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayMActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        hoursM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hoursM.setText("hours");

        miniutesM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        miniutesM.setText("miniutes");

        jComboBoxM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "1", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        jComboBoxM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "24", "25", "30", "35", "40", "45", "50", "55", "60" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setText("Working time per day");

        jTableManagmentWorkingdays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "workingdays", "hours", "miniutes", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableManagmentWorkingdays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableManagmentWorkingdaysMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableManagmentWorkingdays);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("MANAGE WORKING DAYS & HOURS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxM, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(hoursM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(miniutesM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(181, 181, 181)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mondayM)
                                    .addComponent(wednesdayM))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tuesdayM)
                                    .addComponent(thursdayM))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(fridayM)
                                        .addGap(29, 29, 29)
                                        .addComponent(sundayM))
                                    .addComponent(saturdayM)))
                            .addComponent(workingdaysM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workingdaysM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mondayM)
                    .addComponent(tuesdayM)
                    .addComponent(fridayM)
                    .addComponent(sundayM))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wednesdayM)
                    .addComponent(thursdayM)
                    .addComponent(saturdayM))
                .addGap(36, 36, 36)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hoursM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(miniutesM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(161, 161, 161))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
      //  Timetable C = new Timetable();
      // this.hide();
      // C.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tuesdayMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesdayMActionPerformed

    private void fridayMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fridayMActionPerformed

    private void sundayMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sundayMActionPerformed

    private void thursdayMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursdayMActionPerformed

    private void saturdayMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturdayMActionPerformed

    private void wednesdayMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayMActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       /* DefaultTableModel d1 =(DefaultTableModel)jTableManagmentWorkingdays.getModel();
int selectIndex =jTableManagmentWorkingdays.getSelectedRow();


workingdaysM1.setSelectedItem(d1.getValueAt(selectIndex, 0).toString());
jComboBoxM.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
jComboBox2.setSelectedItem(d1.getValueAt(selectIndex, 3).toString());*/
        
        DefaultTableModel d1 =(DefaultTableModel)jTableManagmentWorkingdays.getModel();
       int selectIndex =jTableManagmentWorkingdays.getSelectedRow();
       int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());



int dialogResult = JOptionPane.showConfirmDialog(null,"Do you need the delete","warning",JOptionPane.YES_NO_OPTION);



if(dialogResult == JOptionPane.YES_OPTION)
{
try {

con1 = MY_CONNECTION.getConnection();



pst = con1.prepareStatement("delete from addworkingdays_info where id =?");
pst.setInt(1,id);
pst.executeUpdate();
table_update();
workingdaysM1.setSelectedIndex(0);
jComboBoxM.setSelectedIndex(0);
jComboBox2.setSelectedIndex(0);



//Faculty1.setSelectedIndex(0);



//Department1.setSelectedIndex(0);
//center1.setSelectedIndex(0);



//level1.setSelectedIndex(0);
//Bulding1.setSelectedIndex(0);
//Rank1.setText("");
workingdaysM1.requestFocus();
} catch (SQLException ex) {
Logger.getLogger(Second_Window2.class.getName()).log(Level.SEVERE, null, ex);
} catch (Exception ex) {
Logger.getLogger(Second_Window2.class.getName()).log(Level.SEVERE, null, ex);
}


}

   // }                                                

    //private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
       
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel d1 =(DefaultTableModel)jTableManagmentWorkingdays.getModel();
int selectIndex =jTableManagmentWorkingdays.getSelectedRow();
int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
String workingdays= workingdaysM1.getSelectedItem().toString();
String hoursperdayM = jComboBoxM.getSelectedItem().toString();
String miniutesPerdayM = jComboBox2.getSelectedItem().toString();
           if(mondayM.isSelected()){
           String jTextField3 = mondayM.getText()+"";
          }
           if(tuesdayM.isSelected()){
           String jTextField3 = tuesdayM.getText()+"";
          }
            if(wednesdayM.isSelected()){
           String jTextField3 = wednesdayM.getText()+"";
          }
             if(thursdayM.isSelected()){
           String jTextField3 = thursdayM.getText()+"";
          }
              if(fridayM.isSelected()){
           String jTextField3 = fridayM.getText()+"";
          }
               if(saturdayM.isSelected()){
           String jTextField3 = saturdayM.getText()+"";
          }
                if(sundayM.isSelected()){
           String jTextField3 = sundayM.getText()+"";
          }




try{
    
    
if(workingdaysM1.equals("")){
JOptionPane.showMessageDialog(null,"workingdays is mondotory");
} else if(hoursM.equals("select")){
JOptionPane.showMessageDialog(null,"hours is mondotory");
}else if(miniutesM.equals("select")){
JOptionPane.showMessageDialog(null,"miniutes is mondotory");




}else{
Connection conl =MY_CONNECTION.getConnection();


pst = conl.prepareStatement("update addworkingdays_info set workingdays= ?,hours=?, miniutes=? where id= ?");
pst.setString(1,workingdays);
pst.setString(2,hoursperdayM);
pst.setString(3,miniutesPerdayM);
pst.setInt(4,id);
pst.executeUpdate();
JOptionPane.showMessageDialog(null," Updatedd");
table_update();




workingdaysM1.setSelectedIndex(0);
jComboBoxM.setSelectedIndex(0);
jComboBox2.setSelectedIndex(0);



}
}
    




catch (Exception ex) {
Logger.getLogger(Second_Window2.class.getName()).log(Level.SEVERE, null, ex);
    }                                        
    //}

  
        
        
       // public static void main (String args[]) {
        
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTableManagmentWorkingdaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableManagmentWorkingdaysMouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 =(DefaultTableModel)jTableManagmentWorkingdays.getModel();
        int selectIndex =jTableManagmentWorkingdays.getSelectedRow();
        
        workingdaysM1.setSelectedItem(d1.getValueAt(selectIndex, 1).toString());
        jComboBoxM.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
        jComboBox2.setSelectedItem(d1.getValueAt(selectIndex, 3).toString());

        
        
        
    }//GEN-LAST:event_jTableManagmentWorkingdaysMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         
        First_Window C = new First_Window();
       this.hide();
       C.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBoxMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMActionPerformed
     
   


 
    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second_Window2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox fridayM;
    private javax.swing.JTextField hoursM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableManagmentWorkingdays;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField miniutesM;
    private javax.swing.JCheckBox mondayM;
    private javax.swing.JCheckBox saturdayM;
    private javax.swing.JCheckBox sundayM;
    private javax.swing.JCheckBox thursdayM;
    private javax.swing.JCheckBox tuesdayM;
    private javax.swing.JCheckBox wednesdayM;
    private javax.swing.JComboBox<String> workingdaysM1;
    // End of variables declaration//GEN-END:variables

  //  private void table_update() {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
}


