package timetable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Timetable extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Timetable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lHome = new javax.swing.JLabel();
        btnStudentsH = new javax.swing.JButton();
        btnTagsH = new javax.swing.JButton();
        btnWorkingDaysHoursH = new javax.swing.JButton();
        btnLecturersH = new javax.swing.JButton();
        btnSubjectsH = new javax.swing.JButton();
        btnLocationsH = new javax.swing.JButton();
        btnStatisticsH = new javax.swing.JButton();
        btnSessionsH = new javax.swing.JButton();
        btnGenerateH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lHome.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lHome.setText("Home");

        btnStudentsH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStudentsH.setText("Students");
        btnStudentsH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsHActionPerformed(evt);
            }
        });

        btnTagsH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTagsH.setText("Tags");
        btnTagsH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagsHActionPerformed(evt);
            }
        });

        btnWorkingDaysHoursH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWorkingDaysHoursH.setText("Working Days & Hours");
        btnWorkingDaysHoursH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkingDaysHoursHActionPerformed(evt);
            }
        });

        btnLecturersH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLecturersH.setText("Lecturers");
        btnLecturersH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturersHActionPerformed(evt);
            }
        });

        btnSubjectsH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubjectsH.setText("Subjects");
        btnSubjectsH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectsHActionPerformed(evt);
            }
        });

        btnLocationsH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLocationsH.setText("Locations");
        btnLocationsH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationsHActionPerformed(evt);
            }
        });

        btnStatisticsH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStatisticsH.setText("Statistics");
        btnStatisticsH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsHActionPerformed(evt);
            }
        });

        btnSessionsH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSessionsH.setText("Sessions");
        btnSessionsH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSessionsHActionPerformed(evt);
            }
        });

        btnGenerateH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGenerateH.setText("Generate");
        btnGenerateH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudentsH, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLecturersH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStatisticsH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(btnWorkingDaysHoursH)
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(btnLocationsH, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btnGenerateH, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(507, 507, 507)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnTagsH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSessionsH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubjectsH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lHome, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lHome)
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentsH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTagsH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWorkingDaysHoursH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLecturersH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubjectsH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocationsH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSessionsH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatisticsH, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLecturersHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturersHActionPerformed
        // TODO add your handling code here:
        
        AddLecturer C = new AddLecturer();
        this.hide();
        C.setVisible(true);
        
    }//GEN-LAST:event_btnLecturersHActionPerformed

    private void btnSubjectsHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectsHActionPerformed
        // TODO add your handling code here:
        
        AddSubjects C = new AddSubjects();
        this.hide();
        C.setVisible(true);
        
    }//GEN-LAST:event_btnSubjectsHActionPerformed

    private void btnStudentsHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsHActionPerformed
        // TODO add your handling code here:
        
        Add_Student C = new Add_Student();
       this.hide();
       C.setVisible(true);
        
    }//GEN-LAST:event_btnStudentsHActionPerformed

    private void btnTagsHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagsHActionPerformed
        // TODO add your handling code here:
        
        Add_Tag C = new Add_Tag();
       this.hide();
       C.setVisible(true);
        
    }//GEN-LAST:event_btnTagsHActionPerformed

    private void btnWorkingDaysHoursHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkingDaysHoursHActionPerformed
        // TODO add your handling code here:
        
        First_Window C = new First_Window();
       this.hide();
       C.setVisible(true);
        
    }//GEN-LAST:event_btnWorkingDaysHoursHActionPerformed

    private void btnLocationsHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationsHActionPerformed
        // TODO add your handling code here:
        
        add_locations_window C = new add_locations_window();
       this.hide();
       C.setVisible(true);
        
    }//GEN-LAST:event_btnLocationsHActionPerformed

    private void btnStatisticsHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticsHActionPerformed
        // TODO add your handling code here:
        
        View_Statistics C = new View_Statistics();
       this.hide();
       C.setVisible(true);
        
    }//GEN-LAST:event_btnStatisticsHActionPerformed

    private void btnSessionsHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSessionsHActionPerformed
        // TODO add your handling code here:
        
        Sessions C = new Sessions();
       this.hide();
       C.setVisible(true);
        
        
    }//GEN-LAST:event_btnSessionsHActionPerformed

    private void btnGenerateHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateHActionPerformed
        // TODO add your handling code here:
        
        Generate C = new Generate();
       this.hide();
       C.setVisible(true);
        
    }//GEN-LAST:event_btnGenerateHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateH;
    private javax.swing.JButton btnLecturersH;
    private javax.swing.JButton btnLocationsH;
    private javax.swing.JButton btnSessionsH;
    private javax.swing.JButton btnStatisticsH;
    private javax.swing.JButton btnStudentsH;
    private javax.swing.JButton btnSubjectsH;
    private javax.swing.JButton btnTagsH;
    private javax.swing.JButton btnWorkingDaysHoursH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lHome;
    // End of variables declaration//GEN-END:variables
}
